#lang racket

(require "test-runner.rkt")
(define phym2-testcase `(ρ {* (ρ {h (ρ {g (ρ {+ (ρ {- (ρ {/ (ρ {f (ρ {/ (ρ {* (ρ {ifleq0 (ρ {d (ρ {ifleq0 (ρ {+ (ρ a) (ρ {a (ρ b)})}) (ρ {b (ρ 1)}) (ρ {c (ρ 0)})})}) (ρ {+ (ρ -1) (ρ {- (ρ 0) (ρ {/ (ρ {/ (ρ {ifleq0 (ρ {/ (ρ c) (ρ {* (ρ t) (ρ {ifleq0 (ρ {ifleq0 (ρ d) (ρ {/ (ρ 2.2) (ρ {/ (ρ 0) (ρ {ifleq0 (ρ -22/7) (ρ {ifleq0 (ρ 0) (ρ e) (ρ {* (ρ {- (ρ {+ (ρ {/ (ρ {/ (ρ {/ (ρ {/ (ρ {ifleq0 (ρ o) (ρ 2.2) (ρ {ifleq0 (ρ {ifleq0 (ρ {ifleq0 (ρ {ifleq0 (ρ k) (ρ l) (ρ {/ (ρ i) (ρ j)})}) (ρ m) (ρ 0)}) (ρ n) (ρ -22/7)}) (ρ 0) (ρ h)})}) (ρ {e})}) (ρ 0)}) (ρ -1)}) (ρ g)}) (ρ 0)}) (ρ 1)}) (ρ f)})}) (ρ p)})})}) (ρ q)}) (ρ r) (ρ s)})})}) (ρ u) (ρ v)}) (ρ w)}) (ρ x)})})}) (ρ y)}) (ρ z)}) (ρ a)}) (ρ b)}) (ρ c)}) (ρ d)}) (ρ e)}) (ρ f) (ρ g)}) (ρ h) (ρ i) (ρ j)}) (ρ k)}))
(define phym3-testcase `(ρ {if (ρ {lam {} (ρ {lam {} (ρ {(ρ {lam {} (ρ {var {m = (ρ {lam {} (ρ {+ (ρ {lam {} (ρ {/ (ρ {lam {} (ρ {if (ρ {(ρ {(ρ {var {j = (ρ {(ρ {<= (ρ {(ρ {/ (ρ {(ρ {if (ρ {var {h = (ρ {var {g = (ρ {eq? (ρ {var {f = (ρ {/ (ρ {var {e = (ρ {if (ρ {* (ρ {- (ρ {/ (ρ {+ (ρ {if (ρ {/ (ρ {/ (ρ {if (ρ {if (ρ a) (ρ {lam {a b c d} (ρ b)}) (ρ {lam {e f g} (ρ 1)})}) (ρ {(ρ c) (ρ {lam {h i} (ρ 0)}) (ρ {(ρ -1) (ρ {var {a = (ρ d)} (ρ {lam {j} (ρ true)})}) (ρ {<= (ρ e) (ρ {(ρ 0) (ρ {/ (ρ f) (ρ {(ρ false) (ρ {if (ρ 2.2) (ρ {var {b = (ρ -22/7)} (ρ {(ρ {(ρ {(ρ {(ρ {var {c = (ρ 0)} (ρ {var {d = (ρ false)} (ρ {eq? (ρ -1) (ρ {var (ρ {/ (ρ 2.2) (ρ {var (ρ {if (ρ 0) (ρ {* (ρ 0) (ρ {- (ρ true) (ρ {/ (ρ 0) (ρ {+ (ρ y) (ρ {if (ρ false) (ρ {/ (ρ true) (ρ {/ (ρ {- (ρ {* (ρ {eq? (ρ {<= (ρ w) (ρ {lam {} (ρ {/ (ρ {/ (ρ {/ (ρ {/ (ρ {/ (ρ v) (ρ {lam {} (ρ {if (ρ u) (ρ 2.2) (ρ {if (ρ {if (ρ {if (ρ {if (ρ {if (ρ q) (ρ r) (ρ {(ρ {if (ρ o) (ρ p) (ρ {/ (ρ m) (ρ n)})})})}) (ρ s) (ρ false)}) (ρ t) (ρ 0)}) (ρ true) (ρ -22/7)}) (ρ 0) (ρ l)})})})}) (ρ false)}) (ρ 0)}) (ρ -1)}) (ρ k)})})}) (ρ true)}) (ρ 0)}) (ρ 1)}) (ρ {if (ρ {var (ρ false)}) (ρ {if (ρ {var (ρ -22/7)}) (ρ h) (ρ {var (ρ i)})}) (ρ {+ (ρ {var (ρ 0)}) (ρ j)})})})}) (ρ x)})})})})}) (ρ z)})})})})})})}) (ρ true)}) (ρ 0)}) (ρ 1)}) (ρ g)})}) (ρ a)})})}) (ρ b)})}) (ρ c)}) (ρ d) (ρ e)}) (ρ f)}) (ρ g)}) (ρ h)}) (ρ i) (ρ j)}) (ρ k)}) (ρ l)}) (ρ m)}) (ρ n)}) (ρ o) (ρ p)})} (ρ q)}) (ρ r)})} (ρ s)}) (ρ t)})} (ρ u)})} {i = (ρ v)} (ρ w)}) (ρ x) (ρ y)})}) (ρ z)})}) (ρ a)})})} {k = (ρ b)} {l = (ρ c)} (ρ d)})})}) (ρ e) (ρ f)})}) (ρ g)})}) (ρ h)})})} {n = (ρ i)} {o = (ρ j)} {p = (ρ k)} (ρ l)})})})})}) (ρ m) (ρ n)}))
(define phym4-testcase `(ρ {if (ρ {lam {} (ρ {lam {} (ρ {(ρ {lam {} (ρ {var {new-array = (ρ {lam {} (ρ {if (ρ {(ρ {(ρ {var {eq? = (ρ {(ρ {if (ρ {var {* = (ρ {var {- = (ρ {if (ρ {if (ρ true) (ρ {lam {true false null +} (ρ false)}) (ρ {lam {- * /} (ρ "Hello")})}) (ρ {(ρ null) (ρ {lam {eq? <=} (ρ 1)}) (ρ {(ρ "World") (ρ {var {true = (ρ +)} (ρ {lam {array} (ρ 0)})}) (ρ {if (ρ "Hello") (ρ {var {false = (ρ "World")} (ρ {(ρ -1) (ρ -) (ρ "Hello")})}) (ρ {(ρ 0) (ρ 2.2)})}) (ρ 0)}) (ρ {var {null = (ρ -22/7)} (ρ {var {+ = (ρ 0)} (ρ {if (ρ 1) (ρ {if (ρ 0) (ρ *) (ρ {var (ρ /)})}) (ρ {if (ρ {var (ρ "Hello")}) (ρ "World") (ρ eq?)})})})}) (ρ {var (ρ -1)})}) (ρ "World")})} (ρ 0)})} {/ = (ρ {if (ρ {if (ρ <=) (ρ 0) (ρ 0)}) (ρ 2.2) (ρ -22/7)})} (ρ array)}) (ρ new-array) (ρ aref)})})} {<= = (ρ aset!)} {array = (ρ begin)} (ρ substring)})})}) (ρ a) (ρ b)})})} {aref = (ρ c)} {aset! = (ρ d)} {begin = (ρ e)} (ρ f)})})})})}) (ρ g) (ρ h)}))
(define dfly5-testcase `(ρ {if (ρ {lam {} (ρ {lam {} (ρ {new e (ρ {lam {} (ρ {(ρ {lam {} (ρ {with {e = (ρ {lam {} (ρ {rec {j = (ρ {lam {} (ρ {if (ρ {new d (ρ {new c (ρ {(ρ {new b (ρ {with {b = (ρ {new a (ρ {rec {i = (ρ {new substring (ρ {if (ρ {(ρ {(ρ {with {substring = (ρ {(ρ {rec {h = (ρ {(ρ {if (ρ {with {<= = (ρ {with {eq? = (ρ {rec {g = (ρ {with {/ = (ρ {if (ρ {rec {f = (ρ {rec {e = (ρ {if (ρ {if (ρ {send (ρ {lam {} (ρ {send (ρ {new <= (ρ {send (ρ {(ρ {send (ρ {with {* = (ρ {send (ρ {rec {d = (ρ {send (ρ {if (ρ this) (ρ {lam {true false + -} (ρ true)}) (ρ {lam {* / eq?} (ρ "Hello")})}) (ρ {lam {<= substring} (ρ 1)}) (ρ {lam {a} (ρ 0)}) (ρ {new true (ρ false)}) (ρ {(ρ +) (ρ {new false (ρ "World")}) (ρ {(ρ "Hello") (ρ {with {true = (ρ -)} (ρ {new + (ρ -1)})}) (ρ {rec {true = (ρ *)} (ρ {new - (ρ 0)})}) (ρ {if (ρ "World") (ρ {(ρ 2.2) (ρ {send (ρ {send (ρ /) (ρ {(ρ 0) (ρ eq?)}) (ρ {with {false = (ρ "Hello")} (ρ {(ρ {(ρ {(ρ {(ρ a) (ρ {lam {} (ρ {with {+ = (ρ 1)} (ρ {with {- = (ρ 0)} (ρ {rec {false = (ρ "Hello")} (ρ {with (ρ {if (ρ -1) (ρ {with (ρ {send (ρ "World") (ρ {with (ρ <=)}) (ρ {rec {+ = (ρ 2.2)} (ρ {rec {- = (ρ 0)} (ρ {if (ρ 0) (ρ {rec {c = (ρ w)} (ρ {send (ρ -22/7) (ρ {rec {* = (ρ {with (ρ "Hello")})} (ρ substring)}) (ρ {if (ρ v) (ρ {if (ρ t) (ρ {send (ρ 0) (ρ {if (ρ {with (ρ 0)}) (ρ a) (ρ {with (ρ 1)})}) (ρ {send (ρ r) (ρ {send (ρ {with (ρ {lam {} (ρ {rec {/ = (ρ {rec {eq? = (ρ {rec {<= = (ρ {rec {b = (ρ q)} (ρ {lam {} (ρ {rec {a = (ρ p)} (ρ {(ρ {if (ρ o) (ρ "Hello") (ρ {if (ρ n) (ρ 2.2) (ρ {send (ρ {if (ρ {if (ρ {if (ρ {if (ρ {if (ρ {if (ρ i) (ρ j) (ρ {(ρ {if (ρ g) (ρ h) (ρ {rec {substring = (ρ {send (ρ {send (ρ {send (ρ e) (ρ {new eq?})}) (ρ 0) (ρ 0)}) (ρ 1) (ρ -1)})} (ρ f)})})})}) (ρ k) (ρ {new /})}) (ρ l) (ρ 0)}) (ρ m) (ρ -22/7)}) (ρ {new *}) (ρ "World")}) (ρ 0) (ρ d)}) (ρ "World") (ρ "Hello")})})})})})})})} (ρ 0)})} (ρ -1)})} (ρ "World")})})}) (ρ b) (ρ c)})})}) (ρ s)}) (ρ u)})})}) (ρ x)})})}) (ρ y)})}) (ρ z)})})})})})})}) (ρ 0)}) (ρ -22/7)}) (ρ "World")})}) (ρ b) (ρ c)}) (ρ d)}) (ρ e)}) (ρ f)})}) (ρ g) (ρ h)}) (ρ i)})} (ρ j)}) (ρ k)})} (ρ l)}) (ρ m)})}) (ρ n)})}) (ρ o)})}) (ρ p)}) (ρ q) (ρ r)}) (ρ s) (ρ t)})} (ρ u)})} (ρ v)}) (ρ w) (ρ x)})} (ρ y)})} (ρ z)})} (ρ a)})} (ρ b)}) (ρ c) (ρ d)})})} (ρ e)})})} {a = (ρ f)} (ρ g)})})}) (ρ h) (ρ i)})})} (ρ j)})})} {c = (ρ k)} {d = (ρ l)} (ρ m)})})}) (ρ n)}) (ρ o) (ρ p)}) (ρ q) (ρ r)})})} (ρ s)})})} {f = (ρ t)} {g = (ρ u)} {h = (ρ v)} (ρ w)})})})}) (ρ x) (ρ y) (ρ z)})})}) (ρ a) (ρ b)}))
(define dfly5-testcase2 `(ρ {send (ρ {lam {} (ρ {lam {} (ρ {new e (ρ {lam {} (ρ {(ρ {lam {} (ρ {with {e = (ρ {lam {} (ρ {rec {j = (ρ {lam {} (ρ {if (ρ {lam {} (ρ {send (ρ {new d (ρ {new c (ρ {(ρ {new b (ρ {with {b = (ρ {new a (ρ {rec {i = (ρ {new substring (ρ {if (ρ {new <= (ρ {send (ρ {(ρ {(ρ {with {substring = (ρ {(ρ {rec {h = (ρ {(ρ {if (ρ {(ρ {send (ρ {with {<= = (ρ {with {eq? = (ρ {rec {g = (ρ {with {/ = (ρ {if (ρ {with {* = (ρ {send (ρ {rec {f = (ρ {rec {e = (ρ {if (ρ {rec {d = (ρ {send (ρ {if (ρ {if (ρ {send (ρ {send (ρ this) (ρ {lam {true false + -} (ρ true)}) (ρ {lam {* / eq?} (ρ "Hello")}) (ρ {new true (ρ false)}) (ρ {(ρ +) (ρ {lam {<= substring} (ρ 1)}) (ρ {new false (ρ "World")}) (ρ {(ρ "Hello") (ρ {with {true = (ρ -)} (ρ {lam {a} (ρ 0)})}) (ρ {rec {true = (ρ *)} (ρ {new + (ρ -1)})}) (ρ {if (ρ /) (ρ {new - (ρ 0)}) (ρ {(ρ 2.2) (ρ {send (ρ "World") (ρ {(ρ 0) (ρ eq?)}) (ρ {with {false = (ρ "Hello")} (ρ {(ρ {(ρ {(ρ {with {+ = (ρ 1)} (ρ {with {- = (ρ 0)} (ρ {rec {false = (ρ "Hello")} (ρ {with (ρ {if (ρ "World") (ρ {with (ρ {send (ρ -1) (ρ {with (ρ <=)}) (ρ {rec {+ = (ρ 2.2)} (ρ {rec {- = (ρ 0)} (ρ {if (ρ -22/7) (ρ {rec {c = (ρ a)} (ρ {send (ρ 0) (ρ {rec {* = (ρ {with (ρ "Hello")})} (ρ substring)}) (ρ {if (ρ 0) (ρ {if (ρ y) (ρ {send (ρ w) (ρ {if (ρ {with (ρ 0)}) (ρ a) (ρ {with (ρ 1)})}) (ρ {send (ρ {rec {/ = (ρ {rec {eq? = (ρ {rec {<= = (ρ {rec {b = (ρ v)} (ρ {lam {} (ρ {rec {a = (ρ u)} (ρ {(ρ {if (ρ t) (ρ "World") (ρ {if (ρ s) (ρ 2.2) (ρ {send (ρ {if (ρ {if (ρ r) (ρ {lam {} (ρ {if (ρ p) (ρ {(ρ {if (ρ {if (ρ {if (ρ {if (ρ j) (ρ k) (ρ {lam {} (ρ {if (ρ {if (ρ g) (ρ h) (ρ {rec {substring = (ρ {send (ρ {send (ρ {send (ρ e) (ρ {new eq?})}) (ρ 0)}) (ρ -1) (ρ 0)})} (ρ f)})}) (ρ i) (ρ {new /})})})}) (ρ l) (ρ 0)}) (ρ m) (ρ 1)}) (ρ n) (ρ "World")})}) (ρ o)})}) (ρ q)}) (ρ 0) (ρ d)}) (ρ "Hello") (ρ -22/7)})})})})})})})} (ρ 0)})} (ρ -1)})} (ρ "Hello")}) (ρ {send (ρ {with (ρ {new *})}) (ρ b) (ρ c)}) (ρ "World")})}) (ρ x)}) (ρ z)})})}) (ρ b)})})}) (ρ c)})}) (ρ d)})})})})}) (ρ 0)}) (ρ -22/7)}) (ρ "World")})}) (ρ e) (ρ f)}) (ρ g)})})}) (ρ h)}) (ρ i)}) (ρ j)}) (ρ k) (ρ l)}) (ρ m) (ρ n)}) (ρ o)})} (ρ p)}) (ρ q) (ρ r)})} (ρ s)})} (ρ t)}) (ρ u)})} (ρ v)}) (ρ w) (ρ x)})} (ρ y)})} (ρ z)})} (ρ a)})} (ρ b)}) (ρ c)})}) (ρ d) (ρ e)})})} (ρ f)})})} {a = (ρ g)} (ρ h)})})}) (ρ i)})}) (ρ j) (ρ k)})})} (ρ l)})})} {c = (ρ m)} {d = (ρ n)} (ρ o)})})}) (ρ p)}) (ρ q) (ρ r)}) (ρ s)})}) (ρ t) (ρ u)})})} (ρ v)})})} {f = (ρ w)} {g = (ρ x)} {h = (ρ y)} (ρ z)})})})}) (ρ a) (ρ b) (ρ c)})})}) (ρ d) (ρ e)}))


(run-tests
 "C:\\Users\\Ricky\\Desktop\\Classes\\senior-project\\old-430-submissions\\2164-cpe430\\handin\\Program5"
 'parse-prog
 dfly5-testcase2
 (λ (s) `{,s}))

#;(run-tests
 "C:\\Users\\Ricky\\Downloads\\Program4"
 'parse
 phym4-testcase
 (λ (s) s))

#;(run-tests
 "C:\\Users\\Ricky\\Downloads\\Program3"
 'parse
 phym3-testcase
 (λ (s) s))

#;(run-tests
  "C:\\Users\\Ricky\\Downloads\\Program2"
 'parse
 phym2-testcase
 (λ (s) s))